[pytest]
norecursedirs = .venv demos site-packages ultra_jarvis.egg-info
testpaths = tests
python_files = test_*.py
python_functions = test_*
addopts = --strict-markers --strict-config

markers =
    benchmark: marks tests as benchmark tests

[tool:pytest-benchmark]
min_rounds = 5
max_time = 2.0
compare_fail = 15%